[package]
name = "pdd"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
tokio = { version = "1.45.1", features = ["full"] }
